# Generated by Django 4.2.7 on 2026-03-25 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('small', 'Small Truck (Up to 2 tons)'), ('medium', 'Medium Truck (2-5 tons)'), ('large', 'Large Truck (5-10 tons)'), ('heavy', 'Heavy Truck (10+ tons)')], max_length=20)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('capacity_tons', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dimensions', models.CharField(blank=True, help_text='Length x Width x Height', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='AC, GPS, etc.')),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('interior_image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('current_city', models.CharField(max_length=100)),
                ('current_area', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_to', models.DateField(blank=True, null=True)),
                ('base_price_per_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('base_price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('waiting_charge_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(limit_choices_to={'user_type': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', 'status'], name='vehicles_ve_driver__0ccc06_idx'), models.Index(fields=['vehicle_type', 'status'], name='vehicles_ve_vehicle_34797f_idx'), models.Index(fields=['license_plate'], name='vehicles_ve_license_907c55_idx')],
            },
        ),
    ]
